### ISSUE TITLE
update aframe version break demo

### ISSUE THREAD

**Issue by 7dir** [almossawi/aframe-d3-visualization#1]

**Comment by almossawi** [comment]
Thanks. I've not looked at this project for a while. Would you mind submitting a PR for the fix.

**Comment by 7dir** [comment]
I can not understand why it was broken when I am increased the version number

```
A-Frame Version: 0.3.0
aframe.min.js:227 three Version: ^0.76.1
aframe.min.js:227 WebVR Polyfill Version: 0.9.15
aframe.min.js:6 core:schema:warn Unknown property `fog` for component/system `undefined`. +0ms
aframe.min.js:48 THREE.WebGLRenderer 76
aframe.min.js:123 Uncaught TypeError: Cannot read property 'x' of null
    at s.update (https://aframe.io/releases/0.3.0/aframe.min.js:123:1460)
    at s.tick (https://aframe.io/releases/0.3.0/aframe.min.js:123:1622)
    at https://aframe.io/releases/0.3.0/aframe.min.js:149:5472
    at Array.forEach (native)
    at HTMLElement.value (https://aframe.io/releases/0.3.0/aframe.min.js:149:5434)
    at HTMLElement.value (https://aframe.io/releases/0.3.0/aframe.min.js:149:5614)
    at e (https://aframe.io/releases/0.3.0/aframe.min.js:149:4915)
    at HTMLElement.<anonymous> (https://aframe.io/releases/0.3.0/aframe.min.js:149:5026)
    at Object.module.exports.fireEvent (https://aframe.io/releases/0.3.0/aframe.min.js:271:791)
    at https://aframe.io/releases/0.3.0/aframe.min.js:139:2516
aframe.min.js:123 Uncaught TypeError: Cannot read property 'x' of null
    at s.update (https://aframe.io/releases/0.3.0/aframe.min.js:123:1460)
    at s.tick (https://aframe.io/releases/0.3.0/aframe.min.js:123:1622)
    at https://aframe.io/releases/0.3.0/aframe.min.js:149:5472
    at Array.forEach (native)
    at HTMLElement.value (https://aframe.io/releases/0.3.0/aframe.min.js:149:5434)
    at HTMLElement.value (https://aframe.io/releases/0.3.0/aframe.min.js:149:5614)
    at e (https://aframe.io/releases/0.3.0/aframe.min.js:149:4915)
    at HTMLElement.<anonymous> (https://aframe.io/releases/0.3.0/aframe.min.js:149:5026)
    at Object.module.exports.fireEvent (https://aframe.io/releases/0.3.0/aframe.min.js:271:791)
    at https://aframe.io/releases/0.3.0/aframe.min.js:139:2516
```

**Comment by rohitkshirsagar** [comment]
Is there any chance you got solutions on this issue.. ? @almossawi @7dir
